// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	productTypes "outlet/v1/bussiness/productTypes"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id, productType
func (_m *Repository) Delete(id int, productType *productTypes.Domain) (*productTypes.Domain, error) {
	ret := _m.Called(id, productType)

	var r0 *productTypes.Domain
	if rf, ok := ret.Get(0).(func(int, *productTypes.Domain) *productTypes.Domain); ok {
		r0 = rf(id, productType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*productTypes.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, *productTypes.Domain) error); ok {
		r1 = rf(id, productType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: id
func (_m *Repository) FindByID(id int) (*productTypes.Domain, error) {
	ret := _m.Called(id)

	var r0 *productTypes.Domain
	if rf, ok := ret.Get(0).(func(int) *productTypes.Domain); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*productTypes.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllProductType provides a mock function with given fields:
func (_m *Repository) GetAllProductType() (*[]productTypes.Domain, error) {
	ret := _m.Called()

	var r0 *[]productTypes.Domain
	if rf, ok := ret.Get(0).(func() *[]productTypes.Domain); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]productTypes.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: productType
func (_m *Repository) Insert(productType *productTypes.Domain) (*productTypes.Domain, error) {
	ret := _m.Called(productType)

	var r0 *productTypes.Domain
	if rf, ok := ret.Get(0).(func(*productTypes.Domain) *productTypes.Domain); ok {
		r0 = rf(productType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*productTypes.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*productTypes.Domain) error); ok {
		r1 = rf(productType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
