// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	paymentMethods "outlet/v1/bussiness/paymentMethods"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id, paymentMethod
func (_m *Repository) Delete(id int, paymentMethod *paymentMethods.Domain) (*paymentMethods.Domain, error) {
	ret := _m.Called(id, paymentMethod)

	var r0 *paymentMethods.Domain
	if rf, ok := ret.Get(0).(func(int, *paymentMethods.Domain) *paymentMethods.Domain); ok {
		r0 = rf(id, paymentMethod)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paymentMethods.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, *paymentMethods.Domain) error); ok {
		r1 = rf(id, paymentMethod)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: id
func (_m *Repository) FindByID(id int) (*paymentMethods.Domain, error) {
	ret := _m.Called(id)

	var r0 *paymentMethods.Domain
	if rf, ok := ret.Get(0).(func(int) *paymentMethods.Domain); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paymentMethods.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllPaymentMethod provides a mock function with given fields:
func (_m *Repository) GetAllPaymentMethod() (*[]paymentMethods.Domain, error) {
	ret := _m.Called()

	var r0 *[]paymentMethods.Domain
	if rf, ok := ret.Get(0).(func() *[]paymentMethods.Domain); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]paymentMethods.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: productType
func (_m *Repository) Insert(productType *paymentMethods.Domain) (*paymentMethods.Domain, error) {
	ret := _m.Called(productType)

	var r0 *paymentMethods.Domain
	if rf, ok := ret.Get(0).(func(*paymentMethods.Domain) *paymentMethods.Domain); ok {
		r0 = rf(productType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paymentMethods.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*paymentMethods.Domain) error); ok {
		r1 = rf(productType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
